services:
  app:
    container_name: dota-shuffle-angular
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: "https://metrics.luis122448.dev"
        WS_URL: "wss://metrics.luis122448.dev"
    environment:
        API_URL: "https://metrics.luis122448.dev"
        WS_URL: "wss://metrics.luis122448.dev"
    ports:
      - "4203:4203"
