services:
  app:
    container_name: dota-shuffle-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env: production
    environment:
      API_URL_METRICS: ${API_URL_METRICS}
      WS_URL_METRICS: ${WS_URL_METRICS}
    ports:
      - "4203:80"
