apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: my-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dota-shuffle
  template:
    metadata:
      labels:
        app: dota-shuffle
    spec:
      containers:
      - name: dota-shuffle-container
        image: harbor.bbg.pe/my-portfolio/dota-shuffle-frontend:production
        ports:
        - containerPort: 80
        env:
        - name: API_URL_METRICS
          valueFrom:
            configMapKeyRef:
              name: dota-shuffle-config
              key: API_URL_METRICS
        - name: WS_URL_METRICS
          valueFrom:
            configMapKeyRef:
              name: dota-shuffle-config
              key: WS_URL_METRICS
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
