apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-portfolio
spec:
  type: ClusterIP
  selector:
    app: dota-shuffle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
